#!bin/bash
# new AI software stack ubuntu 18.04 installation script
# thai.vo@hpe.com

# copy group,hosts,sudoers,nsswitch.conf,fstab from hpcgate into your root's home dirctory 
# 
scp \root@10.100.0.5:/etc/\{group,hosts,sudoers,nsswitch.conf,fstab} /root
echo completed copying over hpcgate files

# saving the orgianl group,hosts,sudoers,nsswitch.conf,fstab as backup
#
mv /etc/group /etc/group.old
mv /etc/hosts /etc/hosts.old
mv /etc/nsswitch.conf /etc/nsswitch.conf.old
mv /etc/sudoers /etc/sudoers.old
mv /etc/fstab /etc/fstab.old
echo completed backing up /etc files

# move hpcgate file to /etc/
#
mv /root/group /etc/
mv /root/hosts /etc/
mv /root/nsswitch.conf /etc/
mv /root/sudoers /etc/
mv /root/fstab /etc/
echo completed moving hpcgate files to /etc

# copying over the orginal fstab into the new fstab
#
cat /etc/fstab.old >> /etc/fstab
echo copying over the old fstab into the new fstab

# removing unwanted entry in fstab from hpcgate version
#
sed "/UUID=0c48e174-f76a-47e1-8472-89f2b80df190/d" /etc/fstab
sed "/UUID=741545ea-fd09-49eb-85a5-de411a60be30/d" /etc/fstab
sed "/UUID=94917f16-d92b-49e5-8801-5d03867a5dd4/d"  /etc/fstab
sed "/UUID=8c71c7f4-a12d-4981-b1d2-84f9115a46e3/d" /etc/fstab
sed "//dev/sdb1/d" /etc/fstab
sed "//dev/sdc1/d" /etc/fstab
sed "//dev/sdd1/d" /etc/fstab
sed "//dev/sde1/d" /etc/fstab
sed "//dev/sdf1/d" /etc/fstab
echo completed of removal of hpcgate mounts and UUID in fstab

# remove statoverride which affect installing packages
#
yes | rm /var/lib/dpkg/statoverride
echo completed removed of statoverride

# create new mount point directories
#
mkdir /apps /home /scratch /mops /ml
echo completed creating mount point

# install nfs for mount point above
#
sudo apt-get install nfs-common
echo completed installation of nfs

# mounting all in fstab entry
#
mount -a
echo completed mounting entry of fstab

# enable root login and restart ssh daemon
#
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config 
systemctl restart sshd

# disable auto update
#
sed -i 's/APT::Periodic::Unattended-Upgrade "1";/ APT::Periodic::Unattended-Upgrade "0";/' /etc/apt/apt.conf.d/20auto-upgrades && sed -i 's/APT::Periodic::Update-Package-Lists "1";/APT::Periodic::Update-Package-Lists "0";/' /etc/apt/apt.conf.d/20auto-upgrades
echo completed disable auto

# blacklist nouveau driver for nvidia driver to be installed
#
echo "blacklist nouveau" >> /etc/modprobe.d/blacklist-nouveau.conf
echo "options nouveau modeset=0" >> /etc/modprobe.d/blacklist-nouveau.conf
echo completed blacklist of nouveau

# Regenerate the kernel initramfs
#
update-initramfs -u

# Install GNU Compiler Collection for Nvidia driver
#
yes | apt-get install gcc


