#!/bin/bash
# While loop function to install hp-scripting-tools (conrep)
counter=100
while [ $counter -le 144 ]
do
 cinstallman --yum-node --node cronusn$counter --repo-group rhel76-x86_64-mel-4.5 install hp-scripting-tools
 ((counter++))
 echo cronusn$counter DONE!!!
done
echo All DONE!!!
